//! Stable numeric indexes for every control id a song code can carry.
//!
//! Song codes intern control ids as `u16` indexes into `SONG_ID_TABLE`
//! instead of spelling each id out, so the table's order is part of the
//! on-disk format.
//!
//! APPEND-ONLY. Never reorder an entry, never remove one, never reuse an
//! index for a different control. A new control appends its id at the end;
//! a retired control keeps its slot forever so old codes keep decoding.
//! The table is deliberately NOT derived from `all_specs()` — registry
//! order is free to change, this order is not.
//!
//! `song_ids_cover_every_registry_control` fails the build if a registry
//! control is missing here, so a new control can never become unsaveable.
const SONG_ID_TABLE: &[&str] = &[
    "pad.level",
    "pad.attack_time",
    "pad.release_time",
    "pad.type",
    "pad.chord_bars",
    "pad.chord_count",
    "pad.progression",
    "pad.reverb_mix",
    "pad.stereo_width",
    "pad.detune",
    "pad.octave_mix",
    "pad.chord1_degree",
    "pad.chord1_accidental",
    "pad.chord1_quality",
    "pad.chord1_extension",
    "pad.chord1_inversion",
    "pad.chord2_degree",
    "pad.chord2_accidental",
    "pad.chord2_quality",
    "pad.chord2_extension",
    "pad.chord2_inversion",
    "pad.chord3_degree",
    "pad.chord3_accidental",
    "pad.chord3_quality",
    "pad.chord3_extension",
    "pad.chord3_inversion",
    "pad.chord4_degree",
    "pad.chord4_accidental",
    "pad.chord4_quality",
    "pad.chord4_extension",
    "pad.chord4_inversion",
    "pad.chord5_degree",
    "pad.chord5_accidental",
    "pad.chord5_quality",
    "pad.chord5_extension",
    "pad.chord5_inversion",
    "pad.chord6_degree",
    "pad.chord6_accidental",
    "pad.chord6_quality",
    "pad.chord6_extension",
    "pad.chord6_inversion",
    "pad.chord7_degree",
    "pad.chord7_accidental",
    "pad.chord7_quality",
    "pad.chord7_extension",
    "pad.chord7_inversion",
    "pad.chord8_degree",
    "pad.chord8_accidental",
    "pad.chord8_quality",
    "pad.chord8_extension",
    "pad.chord8_inversion",
    "perc.level",
    "perc.filter",
    "perc.decay_ms",
    "perc.interval_beats",
    "perc.offset_beats",
    "perc.swing",
    "bass.level",
    "bass.cutoff",
    "bass.attack_time",
    "bass.decay_time",
    "bass.type",
    "bass.interval_beats",
    "bass.offset_beats",
    "bass.rhythm",
    "bass.octave",
    "bass.drive",
    "kick.level",
    "kick.filter",
    "kick.pitch_decay_ms",
    "kick.amp_decay_ms",
    "kick.type",
    "kick.interval_beats",
    "kick.offset_beats",
    "kick.start_freq",
    "kick.click",
    "kick.drive",
    "tonal.level",
    "tonal.attack",
    "tonal.decay",
    "tonal.synth_type",
    "tonal.octave",
    "tonal.phrase",
    "tonal.rate_beats",
    "tonal.step_interval_beats",
    "tonal.offset_beats",
    "tonal.swing",
    "tonal.randomness",
    "tonal.evolve_rate",
    "tonal.reverb_mix",
    "clap.level",
    "clap.filter",
    "clap.decay_ms",
    "clap.interval_beats",
    "clap.offset_beats",
    "clap.slap_count",
    "clap.slap_spread_ms",
    "clap.room",
    "clap.body",
    "arp.gain",
    "arp.attack",
    "arp.decay",
    "arp.type",
    "arp.rate_beats",
    "arp.offset_beats",
    "arp.swing",
    "arp.pattern",
    "arp.octaves",
    "arp.reverb_mix",
    "macro.1",
    "macro.2",
    "macro.3",
    "macro.4",
    "master.bpm",
    "master.level",
    "master.drive",
    "master.comp_amount",
    "master.comp_release_ms",
    "master.tone",
    "master.tune",
    "master.comp_threshold",
    "master.comp_ratio",
    "master.comp_makeup",
    "pad.slot1.kind",
    "pad.slot1.amount",
    "pad.slot1.time",
    "pad.slot2.kind",
    "pad.slot2.amount",
    "pad.slot2.time",
    "pad.slot3.kind",
    "pad.slot3.amount",
    "pad.slot3.time",
    "pad.slot4.kind",
    "pad.slot4.amount",
    "pad.slot4.time",
    "pad.slot5.kind",
    "pad.slot5.amount",
    "pad.slot5.time",
    "pad.slot6.kind",
    "pad.slot6.amount",
    "pad.slot6.time",
    "pad.slot7.kind",
    "pad.slot7.amount",
    "pad.slot7.time",
    "pad.slot8.kind",
    "pad.slot8.amount",
    "pad.slot8.time",
    "perc.slot1.kind",
    "perc.slot1.amount",
    "perc.slot1.time",
    "perc.slot2.kind",
    "perc.slot2.amount",
    "perc.slot2.time",
    "perc.slot3.kind",
    "perc.slot3.amount",
    "perc.slot3.time",
    "perc.slot4.kind",
    "perc.slot4.amount",
    "perc.slot4.time",
    "perc.slot5.kind",
    "perc.slot5.amount",
    "perc.slot5.time",
    "perc.slot6.kind",
    "perc.slot6.amount",
    "perc.slot6.time",
    "perc.slot7.kind",
    "perc.slot7.amount",
    "perc.slot7.time",
    "perc.slot8.kind",
    "perc.slot8.amount",
    "perc.slot8.time",
    "bass.slot1.kind",
    "bass.slot1.amount",
    "bass.slot1.time",
    "bass.slot2.kind",
    "bass.slot2.amount",
    "bass.slot2.time",
    "bass.slot3.kind",
    "bass.slot3.amount",
    "bass.slot3.time",
    "bass.slot4.kind",
    "bass.slot4.amount",
    "bass.slot4.time",
    "bass.slot5.kind",
    "bass.slot5.amount",
    "bass.slot5.time",
    "bass.slot6.kind",
    "bass.slot6.amount",
    "bass.slot6.time",
    "bass.slot7.kind",
    "bass.slot7.amount",
    "bass.slot7.time",
    "bass.slot8.kind",
    "bass.slot8.amount",
    "bass.slot8.time",
    "kick.slot1.kind",
    "kick.slot1.amount",
    "kick.slot1.time",
    "kick.slot2.kind",
    "kick.slot2.amount",
    "kick.slot2.time",
    "kick.slot3.kind",
    "kick.slot3.amount",
    "kick.slot3.time",
    "kick.slot4.kind",
    "kick.slot4.amount",
    "kick.slot4.time",
    "kick.slot5.kind",
    "kick.slot5.amount",
    "kick.slot5.time",
    "kick.slot6.kind",
    "kick.slot6.amount",
    "kick.slot6.time",
    "kick.slot7.kind",
    "kick.slot7.amount",
    "kick.slot7.time",
    "kick.slot8.kind",
    "kick.slot8.amount",
    "kick.slot8.time",
    "tonal.slot1.kind",
    "tonal.slot1.amount",
    "tonal.slot1.time",
    "tonal.slot2.kind",
    "tonal.slot2.amount",
    "tonal.slot2.time",
    "tonal.slot3.kind",
    "tonal.slot3.amount",
    "tonal.slot3.time",
    "tonal.slot4.kind",
    "tonal.slot4.amount",
    "tonal.slot4.time",
    "tonal.slot5.kind",
    "tonal.slot5.amount",
    "tonal.slot5.time",
    "tonal.slot6.kind",
    "tonal.slot6.amount",
    "tonal.slot6.time",
    "tonal.slot7.kind",
    "tonal.slot7.amount",
    "tonal.slot7.time",
    "tonal.slot8.kind",
    "tonal.slot8.amount",
    "tonal.slot8.time",
    "clap.slot1.kind",
    "clap.slot1.amount",
    "clap.slot1.time",
    "clap.slot2.kind",
    "clap.slot2.amount",
    "clap.slot2.time",
    "clap.slot3.kind",
    "clap.slot3.amount",
    "clap.slot3.time",
    "clap.slot4.kind",
    "clap.slot4.amount",
    "clap.slot4.time",
    "clap.slot5.kind",
    "clap.slot5.amount",
    "clap.slot5.time",
    "clap.slot6.kind",
    "clap.slot6.amount",
    "clap.slot6.time",
    "clap.slot7.kind",
    "clap.slot7.amount",
    "clap.slot7.time",
    "clap.slot8.kind",
    "clap.slot8.amount",
    "clap.slot8.time",
    "arp.slot1.kind",
    "arp.slot1.amount",
    "arp.slot1.time",
    "arp.slot2.kind",
    "arp.slot2.amount",
    "arp.slot2.time",
    "arp.slot3.kind",
    "arp.slot3.amount",
    "arp.slot3.time",
    "arp.slot4.kind",
    "arp.slot4.amount",
    "arp.slot4.time",
    "arp.slot5.kind",
    "arp.slot5.amount",
    "arp.slot5.time",
    "arp.slot6.kind",
    "arp.slot6.amount",
    "arp.slot6.time",
    "arp.slot7.kind",
    "arp.slot7.amount",
    "arp.slot7.time",
    "arp.slot8.kind",
    "arp.slot8.amount",
    "arp.slot8.time",
];

/// Index of `id` in the song-code id table, or `None` if the control has
/// never been assigned one.
pub(crate) fn song_id_index(id: &str) -> Option<u16> {
    SONG_ID_TABLE
        .iter()
        .position(|entry| *entry == id)
        .map(|index| index as u16)
}

/// The control id at `index`, or `None` if a code names a slot this build
/// does not know about.
pub(crate) fn song_id_at(index: u16) -> Option<&'static str> {
    SONG_ID_TABLE.get(index as usize).copied()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fluid::registry::all_specs;
    use std::collections::BTreeSet;

    #[test]
    fn song_ids_cover_every_registry_control() {
        let missing: Vec<_> = all_specs()
            .map(|spec| spec.id)
            .filter(|id| song_id_index(id).is_none())
            .collect();
        assert!(
            missing.is_empty(),
            "append these control ids to SONG_ID_TABLE so they can be saved: {missing:?}"
        );
    }

    #[test]
    fn song_id_table_has_no_duplicates() {
        let mut seen = BTreeSet::new();
        for id in SONG_ID_TABLE {
            assert!(seen.insert(*id), "duplicate song id table entry: {id}");
        }
    }

    #[test]
    fn song_id_index_and_lookup_are_inverses() {
        for (index, id) in SONG_ID_TABLE.iter().enumerate() {
            let index = index as u16;
            assert_eq!(song_id_index(id), Some(index));
            assert_eq!(song_id_at(index), Some(*id));
        }
        assert_eq!(song_id_at(SONG_ID_TABLE.len() as u16), None);
    }
}
